project:
  type: website
  output-dir: ../docs/
  resources: "data/*"

website:
  title: "Airline Performance Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: The Story
      - href: code.ipynb
        text: Code

format:
  html:
    theme: minty
    # css: styles.css
    toc: true



