project:
  type: website
  output-dir: ../docs/
  resources: "data/*"

website:
  title: "Airline Performance Analysis"
  favicon: media/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: The Story
      - href: code.ipynb
        text: Python Code
      - href: sql.qmd
        text: SQL Queries

format:
  html:
    theme: minty
    toc: true



